## 1. 前言

首先，先描述了整个RPC的流程如何，以及client/server端是如何处理RPC过程中发生的IOException/NotLeaderException的，以及自己看到的代码逻辑中的问题和对应的JIRA

先说server端

server端在收到来自client的的请求后，代码在RaftClientProtocolService$AppendRequestStreamObserver.onNext()方法中

```java
@Override
public void onNext(RaftClientRequestProto request) {
    try {
        final RaftClientRequest r = ClientProtoUtils.toRaftClientRequest(request);
        final PendingAppend p = new PendingAppend(r);
        slidingWindow.receivedRequest(p, this::processClientRequestAsync);
    } catch (Throwable e) {
        responseError(e, () -> "onNext for " + ClientProtoUtils.toString(request));
    }
}
```

有关processClientRequestAsync()方法如下

```java
void processClientRequestAsync(PendingAppend pending) {
    try {
        protocol.submitClientRequestAsync(pending.getRequest()
                                         ).thenAcceptAsync(reply -> slidingWindow.receiveReply(
            pending.getSeqNum(), reply, this::sendReply, this::processClientRequestAsync)
                                                          ).exceptionally(exception -> {
            // TODO: the exception may be from either raft or state machine.
            // Currently we skip all the following responses when getting an
            // exception from the state machine.
            responseError(exception, () -> "processClientRequestAsync for " + pending.getRequest());
            return null;
        });
    } catch (IOException e) {
        throw new CompletionException("Failed processClientRequestAsync for " + pending.getRequest(), e);
    }
}
```

protocol.submitClientRequestAsync()方法在RaftServerImpl方法中，定义如下

```java
public CompletableFuture<RaftClientReply> submitClientRequestAsync(
      RaftClientRequest request) throws IOException {
    assertLifeCycleState(RUNNING);
    LOG.debug("{}: receive client request({})", getId(), request);
    if (request.is(RaftClientRequestProto.TypeCase.STALEREAD)) {
      return staleReadAsync(request);
    }

    // first check the server's leader state
    CompletableFuture<RaftClientReply> reply = checkLeaderState(request, null);
    if (reply != null) {
      return reply;
    }

    // let the state machine handle read-only request from client
    final StateMachine stateMachine = getStateMachine();
    if (request.is(RaftClientRequestProto.TypeCase.READ)) {
      // TODO: We might not be the leader anymore by the time this completes.
      // See the RAFT paper section 8 (last part)
      return processQueryFuture(stateMachine.query(request.getMessage()), request);
    }

    // query the retry cache
    RetryCache.CacheQueryResult previousResult = retryCache.queryCache(
        request.getClientId(), request.getCallId());
    if (previousResult.isRetry()) {
      // if the previous attempt is still pending or it succeeded, return its
      // future
      return previousResult.getEntry().getReplyFuture();
    }
    final RetryCache.CacheEntry cacheEntry = previousResult.getEntry();

    // TODO: this client request will not be added to pending requests until
    // later which means that any failure in between will leave partial state in
    // the state machine. We should call cancelTransaction() for failed requests
    TransactionContext context = stateMachine.startTransaction(request);
    if (context.getException() != null) {
      RaftClientReply exceptionReply = new RaftClientReply(request,
          new StateMachineException(getId(), context.getException()), getCommitInfos());
      cacheEntry.failWithReply(exceptionReply);
      return CompletableFuture.completedFuture(exceptionReply);
    }
    return appendTransaction(request, context, cacheEntry);
  }
```

1. NotLeaderException

   在RaftServerImpl.submitClientRequestAsync()方法中，首先会调用checkLeaderState()方法，当此server不是leader时，会返回一个带有NotLeaderException的reply，但是其为Completed状态，并不是CompleteExceptionally状态

   ```java
   CompletableFuture<RaftClientReply> reply = checkLeaderState(request, null);
   if (reply != null) {
       return reply;
   }
   ```

   ```java
   if (!isLeader()) {
         NotLeaderException exception = generateNotLeaderException();
         final RaftClientReply reply = new RaftClientReply(request, exception, getCommitInfos());
         return RetryCache.failWithReply(reply, entry);
   ```

   这样子，回到processClientRequestAsync()方法，回执行thenAcceptAsyn()方法，将对应的reply通过onNext()方法发送给客户端

2. IOException

   在processClientRequestAsync()中，调用了RaftServerImpl.submitClientRequestAsync()方法，该方法会抛出IOException。当发生IOException时，processClientRequestAsync()方法会throw CompletionException，该exception在onNext()方法被捕捉，调用responseError()方法，通过onError()方法将异常发送给客户端

再看客户端

客户端的发送逻辑在RaftClientImpl中的sendRequestWithRetryAsync()方法中，这里需要注意的是，在sendRequestAsyn()方法之后，调用了thenCompose()方法，这是接收到reply之后的处理逻辑

```java
private CompletableFuture<RaftClientReply> sendRequestWithRetryAsync(
      PendingAsyncRequest pending) {
    final RaftClientRequest request = pending.newRequest();
    final CompletableFuture<RaftClientReply> f = pending.getReplyFuture();
    return sendRequestAsync(request).thenCompose(reply -> {
        if (reply == null) {
            LOG.debug("schedule a retry in {} for {}", retryInterval, request);
            scheduler.onTimeout(retryInterval,
                                () -> getSlidingWindow(request).retry(pending, this::sendRequestWithRetryAsync),
                                LOG, () -> "Failed to retry " + request);
        } else {
            f.complete(reply);
        }
        return f;
    });
}
```

该方法调用sendReqeustAsync()方法，同理，这里需要注意的是，在sendRequestAsync()方法后调用了thenApply()方法，这里是接受到reply之后的处理逻辑

```java
private CompletableFuture<RaftClientReply> sendRequestAsync(
      RaftClientRequest request) {
    LOG.debug("{}: send* {}", clientId, request);
    return clientRpc.sendRequestAsync(request).thenApply(reply -> {
        LOG.debug("{}: receive* {}", clientId, reply);
        reply = handleNotLeaderException(request, reply);
        if (reply != null) {
            getSlidingWindow(request).receiveReply(
                request.getSeqNum(), reply, this::sendRequestWithRetryAsync);
        }
        return reply;
    }).exceptionally(e -> {
        LOG.debug("{}: Failed {} with {}", clientId, request, e);
        e = JavaUtils.unwrapCompletionException(e);
        if (e instanceof GroupMismatchException) {
            throw new CompletionException(e);
        } else if (e instanceof IOException) {
            handleIOException(request, (IOException)e, null);
        } else {
            throw new CompletionException(e);
        }
        return null;
    });
}
```

这里调用GrpcClientRpc.sendRequestAsync()方法

```java
public CompletableFuture<RaftClientReply> sendRequestAsync(
      RaftClientRequest request) {
    final RaftPeerId serverId = request.getServerId();
    try {
        final RaftClientProtocolClient proxy = getProxies().getProxy(serverId);
        // Reuse the same grpc stream for all async calls.
        return proxy.getAppendStreamObservers().onNext(request);
    } catch (IOException e) {
        return JavaUtils.completeExceptionally(e);
    }
}
```

最终调用RaftClientProtocolClient$AsyncStreamObservers.onNext()方法

```java
CompletableFuture<RaftClientReply> onNext(RaftClientRequest request) {
      final Map<Long, CompletableFuture<RaftClientReply>> map = replies.get();
      if (map == null) {
        return JavaUtils.completeExceptionally(new IOException("Already closed."));
      }
      final CompletableFuture<RaftClientReply> f = new CompletableFuture<>();
      //这里加将对应的CompletableFuture放入到Map中了
      CollectionUtils.putNew(request.getCallId(), f, map,
          () -> getName() + ":" + getClass().getSimpleName());
      try {
        requestStreamObserver.onNext(ClientProtoUtils.toRaftClientRequestProto(request));
        scheduler.onTimeout(requestTimeoutDuration, () -> timeoutCheck(request), LOG,
            () -> "Timeout check failed for client request: " + request);
      } catch(Throwable t) {
        handleReplyFuture(request.getCallId(), future -> future.completeExceptionally(t));
      }
      return f;
    }
```

那么接下来，就要看client侧接收reply的处理逻辑，这部分在RaftClientProtocolClient$AsyncStreamObservers.AsyncStreamObservers.replyStreamObserver.onNext()和onError()方法中

```java
public void onNext(RaftClientReplyProto proto) {
    final long callId = proto.getRpcReply().getCallId();
    try {
        final RaftClientReply reply = ClientProtoUtils.toRaftClientReply(proto);
        final NotLeaderException nle = reply.getNotLeaderException();
        if (nle != null) {
            completeReplyExceptionally(nle, NotLeaderException.class.getName());
            return;
        }
        handleReplyFuture(callId, f -> f.complete(reply));
    } catch (Throwable t) {
        handleReplyFuture(callId, f -> f.completeExceptionally(t));
    }
}

public void onError(Throwable t) {
    final IOException ioe = RaftGrpcUtil.unwrapIOException(t);
    completeReplyExceptionally(ioe, "onError");
}
```

server在处理NotLeaderException时，是通过onNext()方法发给client侧的，那么这里就是走的onNext()方法，在onNext()方法中，会判断是否发生NotLeaderException，如果发生了，那么会将reply的Completable状态修改为CompletableExceptionally，那么在RaftClientImpl.sendRequestAsync()方法中，继续执行的是exceptionally()方法而不是thenApply()方法。这里有一个bug，在thenApply()方法中对NotLeaderException进行了判断，实际上，代码并不会走到这里，而是直接进入了sendRequestAsync()方法中

```
这块困扰了很久，一直以为自己没有读懂代码上的逻辑，也怀疑过是不是bug，看了0.3.0/0.4.0的版本，但是这个问题一直都存在，还好看到了对应的jira，即RATIS-841，在1.0.0版本中对该bug进行了修复
```

在处理IOException时，是通过onError()方法接收到reply的，将reply的状态修改为CompletableExceptionally，那么在RaftClientImpl.sendRequestAsync()方法中，继续执行的是exceptionally()方法

根据Ratis140中所描述的

```
Another problem we fix here is: when the client fails over to from an old leader to a new leader, the client should send retries in the same order.
```

这句话出现在r140_20171204.patch之后，那么相关的代码改动就是为了解决这个问题的。

### 1. 有关Client类中的两个first实例变量

* firstSeqNum用来标识第一个请求的seqNum
* firstReplied用来标识第一个请求是否已经得到了回复

关于这两个实例变量的处理逻辑主要在sendOrDelayRequest()方法中。

入口方法在submitNewRequest()方法中，该方法首先构造REQUEST请求，将该请求放入RequestMap中等待发送。具体选择立即发送还是推迟发送的逻辑在sendOrDelayRequest()方法中

```java
/**
     * A new request arrives, create it with {@link #nextSeqNum}
     * and then try sending it to the server.
     *
     * @param requestConstructor use seqNum to create a new request.
     * @return the new request.
     */
    public synchronized REQUEST submitNewRequest(
        LongFunction<REQUEST> requestConstructor, Consumer<REQUEST> sendMethod) {
      if (!requests.isEmpty()) {
        Preconditions.assertTrue(nextSeqNum == requests.lastSeqNum() + 1,
            () -> "nextSeqNum=" + nextSeqNum + " but " + this);
      }

      final long seqNum = nextSeqNum++;
      final REQUEST r = requestConstructor.apply(seqNum);
      requests.putNewRequest(r);

      final boolean submitted = sendOrDelayRequest(r, sendMethod);
      LOG.debug("{}: submitting a new request {} in {}? {}",
          requests.getName(), r, this, submitted? "submitted": "delayed");
      return r;
    }

    private boolean sendOrDelayRequest(REQUEST request, Consumer<REQUEST> sendMethod) {
      final long seqNum = request.getSeqNum();
      Preconditions.assertTrue(requests.getNonRepliedRequest(seqNum, "sendOrDelayRequest") == request);

      if (firstReplied) {
        // already received the reply for the first request, submit any request.
        sendMethod.accept(request);
        return true;
      }

      if (firstSeqNum == -1 && seqNum == requests.firstSeqNum()) {
        // first request is not yet submitted and this is the first request, submit it.
        LOG.debug("{}: detect firstSubmitted {} in {}", requests.getName(), request, this);
        firstSeqNum = seqNum;
        sendMethod.accept(request);
        return true;
      }

      // delay other requests
      CollectionUtils.putNew(seqNum, seqNum, delayedRequests, () -> requests.getName() + ":delayedRequests");
      return false;
    }
```

sendOrDelayRequest()方法首先判断第一个请求是否已经得到了leader的回复，如果得到了，那么可以将该请求直接发送；否则判断该请求是否为第一个请求，判断的逻辑有两个：首先，firstSeqNum处在复位的状态，其次，该请求是requestsMap中的第一个请求，如果满足这两个条件，说明该请求是第一个请求，那么可以将该请求直接发送；否则，将请求放入延迟队列中。

这样的代码逻辑是因为client在发送request的过程中，很有可能发生leader的fail over。需要注意的是，leader也是使用SlidingWindow对接收到的request进行按序处理，按序回复，即便如此，依旧会出现reply乱序到达的情况。

假设：

1. leader将reply1 reply2 reply3按序发送给了client
2. 由于reply1 reply2 reply3走的不同的路由，那么在客户端侧，依旧会出现响应乱序到达的情况
3. client按照reply2 reply1 reply3的顺序收到了响应

假设reply2 reply1 reply3均为NotLeaderException，那么分别会调用resetFirstSeqNum()方法，不对，应该只有reply1为NotLeaderException，这部分的逻辑在哪里呢？？？？

这部分要看RaftClient，RaftClientImpl调用sendRequestAsync()方法啊，该方法返回一个CompletableFuture对象，处理reply的逻辑在thenApply()方法中。(这里的理解是错的，因为在sendRequestAsyn()方法中，关于handleNotLeaderException()方法返回值是有描述的: 当reply为null或者存在NotLeaderException的情况下，该方法会返回null，而sendRequestAsyn方法中，当reply为null时，是不会清除Client中对应seqNum的缓存的)。所以正确的入口方法应该在sendAsync()中。可以看到在sendRequestWithRetryAsyn()方法中，处理了reply==null的情况，即发生NotLeaderException的情况，这里时调用的Client.retry()方法

```java
private CompletableFuture<RaftClientReply> sendAsync(
      RaftClientRequest.Type type, Message message, RaftPeerId server) {
    Objects.requireNonNull(message, "message == null");
    try {
      asyncRequestSemaphore.acquire();
    } catch (InterruptedException e) {
      throw new CompletionException(IOUtils.toInterruptedIOException(
          "Interrupted when sending " + message, e));
    }
    final long callId = nextCallId();
    final LongFunction<PendingAsyncRequest> constructor = seqNum -> new PendingAsyncRequest(seqNum,
        seq -> newRaftClientRequest(server, callId, seq, message, type));
    return getSlidingWindow(server).submitNewRequest(constructor, this::sendRequestWithRetryAsync
    ).getReplyFuture(
    ).thenApply(reply -> handleStateMachineException(reply, CompletionException::new)
    ).whenComplete((r, e) -> asyncRequestSemaphore.release());
  }
```

```java
private CompletableFuture<RaftClientReply> sendRequestWithRetryAsync(
      PendingAsyncRequest pending) {
    final RaftClientRequest request = pending.newRequest();
    final CompletableFuture<RaftClientReply> f = pending.getReplyFuture();
    return sendRequestAsync(request).thenCompose(reply -> {
      if (reply == null) {
        LOG.debug("schedule a retry in {} for {}", retryInterval, request);
        scheduler.onTimeout(retryInterval,
            () -> getSlidingWindow(request).retry(pending, this::sendRequestWithRetryAsync),
            LOG, () -> "Failed to retry " + request);
      } else {
        f.complete(reply);
      }
      return f;
    });
  }
```

```java
private CompletableFuture<RaftClientReply> sendRequestAsync(
      RaftClientRequest request) {
    LOG.debug("{}: send* {}", clientId, request);
    return clientRpc.sendRequestAsync(request).thenApply(reply -> {
      LOG.debug("{}: receive* {}", clientId, reply);
      reply = handleNotLeaderException(request, reply);
      if (reply != null) {
        getSlidingWindow(request).receiveReply(
            request.getSeqNum(), reply, this::sendRequestWithRetryAsync);
      }
      return reply;
    }).exceptionally(e -> {
      LOG.debug("{}: Failed {} with {}", clientId, request, e);
      e = JavaUtils.unwrapCompletionException(e);
      if (e instanceof GroupMismatchException) {
        throw new CompletionException(e);
      } else if (e instanceof IOException) {
        handleIOException(request, (IOException)e, null);
      } else {
        throw new CompletionException(e);
      }
      return null;
    });
  }
```

由此可见，处理NotLeaderException的逻辑一部分在handleNotLeaderException()中，一部分在Client.retry()方法中

```java
public synchronized void retry(REQUEST request, Consumer<REQUEST> sendMethod) {
      if (requests.getNonRepliedRequest(request.getSeqNum(), "retry") != request) {
        // out-dated or invalid retry
        LOG.debug("{}: Ignore retry {} in {}", requests.getName(), request, this);
        return;
      }
      final boolean submitted = sendOrDelayRequest(request, sendMethod);
      LOG.debug("{}: submitting a retry {} in {}? {}",
          requests.getName(), request, this, submitted? "submitted": "delayed");
    }
```

retry()方法直接调用的sendOrDelayRequest()方法。因为retry()方法使用synchronized关键词进行了修饰，那么这是一个同步方法。

```java
private boolean sendOrDelayRequest(REQUEST request, Consumer<REQUEST> sendMethod) {
      final long seqNum = request.getSeqNum();
      Preconditions.assertTrue(requests.getNonRepliedRequest(seqNum, "sendOrDelayRequest") == request);

      if (firstReplied) {
        // already received the reply for the first request, submit any request.
        sendMethod.accept(request);
        return true;
      }

      if (firstSeqNum == -1 && seqNum == requests.firstSeqNum()) {
        // first request is not yet submitted and this is the first request, submit it.
        LOG.debug("{}: detect firstSubmitted {} in {}", requests.getName(), request, this);
        firstSeqNum = seqNum;
        sendMethod.accept(request);
        return true;
      }

      // delay other requests
      CollectionUtils.putNew(seqNum, seqNum, delayedRequests, () -> requests.getName() + ":delayedRequests");
      return false;
    }
```

可以看到，在收到leader的reply之后，首先要判断是否发生了NotLeaderException的情况，处理逻辑在handleNotLeaderException()方法中。可以看到这里在HandleIOException中先调用了Client.resetFirstSeqNum()方法，而后sendRequestAsyn()方法调用了Client.receiveReply()方法，那么逻辑实际上还是在SlidingWindow.Client中

```java
/**
   * @return null if the reply is null or it has {@link NotLeaderException};
   *         otherwise return the same reply.
   */
  private RaftClientReply handleNotLeaderException(RaftClientRequest request, RaftClientReply reply) {
    if (reply == null) {
      return null;
    }
    final NotLeaderException nle = reply.getNotLeaderException();
    if (nle == null) {
      return reply;
    }
    refreshPeers(Arrays.asList(nle.getPeers()));
    final RaftPeerId newLeader = nle.getSuggestedLeader() == null ? null
        : nle.getSuggestedLeader().getId();
    handleIOException(request, nle, newLeader);
    return null;
  }

  private void handleIOException(RaftClientRequest request, IOException ioe,
      RaftPeerId newLeader) {
    LOG.debug("{}: suggested new leader: {}. Failed {} with {}",
        clientId, newLeader, request, ioe);
    if (LOG.isTraceEnabled()) {
      LOG.trace("Stack trace", new Throwable("TRACE"));
    }

    getSlidingWindow(request).resetFirstSeqNum();
    if (ioe instanceof LeaderNotReadyException) {
      return;
    }

    final RaftPeerId oldLeader = request.getServerId();
    final boolean stillLeader = oldLeader.equals(leaderId);
    if (newLeader == null && stillLeader) {
      newLeader = CollectionUtils.random(oldLeader,
          CollectionUtils.as(peers, RaftPeer::getId));
    }

    final boolean changeLeader = newLeader != null && stillLeader;
    if (changeLeader) {
      LOG.debug("{}: change Leader from {} to {}", clientId, oldLeader, newLeader);
      this.leaderId = newLeader;
    }
    clientRpc.handleException(oldLeader, ioe, changeLeader);
  }
```

### 2. 解决上述问题

1. leader将reply1 reply2 reply3按序发送给了client
2. 由于reply1 reply2 reply3走的不同的路由，那么在客户端侧，依旧会出现响应乱序到达的情况
3. client按照reply2 reply1 reply3的顺序收到了响应

假设在reply1之前的所有的request都正常收到了reply，那么此时Client中的RequestMap只缓存了req1 req2 req3，当req2到达时，携带着NotLeaderException信息，那么会出发resetFirstSeqNum()方法，此时firstReply==-1，firstSeqNum == -1，那么在sendOrDelayRequest()方法中，就会将该方法放入到delayed队列中，因为retry()方法是同步方法，所以在处理后续到达的rep1 rep3都会等待rep2的处理逻辑完毕。

那么关于handleIOException中对NotLeaderException的处理逻辑为

1. 调用Client.resetFirstSeqNum()，将firstSeqNum和firstReplied都复位
2. 在old leader的reply中可能携带着newLeader的信息
3. 调用RaftClientRpc.handleException()方法

### 3. Ratis-459

首先描述Ratis-459中提到的问题

With some discussion with [ljain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ljain) (thanks!), the following (highly unlikely) hypothetical scenario may lead to the async requests out-of-order.

1. Requests r1-r5 success,
2. Request r6 fails with NotLeader,
3. Request r7 fails with some other IOException
4. r6 is still keeping retrying and a retry of r7 succeeds with s1.

这里描述的是leader failover的问题：

第2步中，当r6收到NotLeader的reply后，会触发changeLeader，将后续的请求发送到newLeader中。当r7收到IOException的reply后，因为没有收到NotLeader的exception，因而只是简单的重试机制，但是这时r6已经修改了newLeader，导致















































